language: node_js
node_js:
- '8'
install:
- npm install datahub-cli
script: data push ./ --published
env:
  global:
    token:
      secure: AJF+PF9DZ81Sp9kw/ucahg1N4lzkYTpoykDdinrhSN4zzy2suVfq9P7fx5WU4Qqu/h4Q4fDlzXcZojkEb3mPuzJrr8szZkFJrtAIBaWhamh9mvSrClZAeV4qwl1g94JAJPkI8D6fH8ssKsm7zVBTNV6+C7HIsmO7IndjmupvrG4Brm5WoetE371yA2kxJGlJy02z5z7C3FA5gqOD6W0IIe0Z5SqAzL4HzOCAGVLtFFfXytnodx6I8ezDPW0UIQCwyOgj1fw56aHtbWH7hTux6WlnCvxT03FWEO74Iu789yM1hn9Dek1i7RjgB1FjYXfyABLPCXlT0/BSuxSj4VCPnQvunao5uGGnvpheiNhHFnrHTpY6gCesyB0plOrAl4o8i4MoMxJzDMMomzCeMJHDEgI4qKFC1a+B1zXDQqL/n2jzK2wsJJ/vyhc9EushA8mAHfnXFGXciIYViqJoJN3FBzt7Ai2ChMqZtTHQ/I4omQ1tI2SMFOJ4TamQfPSvFX977vlwyNRYRX1PXv0oCEmjTriaAW2oL0lNPcRyb06f1rhB2cyfO/LJW7cD7f6Ekdmwr4pfaWmy0Vx/xAp4awiXBzErgSGqDdmLguUS5aEn57xRw/t5MZL6FOW8uGjmJ4KhPCxaLNK779IhUfX3GtJU1fB7OYTEpnGHq7FxFBi4Voo=
    profile:
      id: examples
      username: examples