language: node_js
node_js:
- '8'
before_install:
source ./travis-env.sh
install:
- npm install datahub-cli
script: data push ./ --published
env:
  global:
    profile: { "id":"examples", "username":"examples"}
  TRAVIS_SECURE_ENV_VARS: true